### ISSUE TITLE
Add ability to use codec arguments 

### ISSUE THREAD

**Issue by bytebutcher** [bytebutcher/snippet#7]
Currently codecs can not have any arguments. 
```
snippet -f "<arg:b64>" arg=test
```
Adding argument support adds more flexibility. However, this requires to adjust the snippet format string.
```
snippet -f "<arg|ljust:"10">
```
A nice side-effect: The optional separator when handling repeatables can be removed.
```
snippet -f "<arg,...>" arg=1 2 3
snippet -f "<arg...|join:","> arg=1 2 3
```
A overview of codecs can be viewed here:
* https://docs.djangoproject.com/en/1.11/ref/templates/builtins/

Currently the whole snippet format string is parsed using regular expressions.
It might be time to change the parsing method in favor of a a full fletched grammar parser:
* https://github.com/andychase/reparse
* http://lrparsing.sourceforge.net/doc/examples/lrparsing-sqlite.py

**Comment by datenwurm** [comment]
Here's the source code to the django templates:
* https://github.com/django/django/blob/master/django/template/defaultfilters.py

**Comment by bytebutcher** [comment]
Implement with version 2.0.0
